name: CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mount caches
        uses: actions/cache@v3
        with:
          path: |
            "/home/runner/.cache/bazel"
            "/home/runner/.m2/repository"
          key: caches-${{ runner.os }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: "See settings"
        run: cat /home/runner/.m2/settings.xml
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod a+x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Sync Bazel Dependencies
        run: |
          "${GITHUB_WORKSPACE}/scripts/ci-sync.sh"
        timeout-minutes: 10
      - name: Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //...
      - name: Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test //...
